### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by rhoef** [rhoef/afw#2]
Running the import in a thread can cause the following error

```
Traceback (most recent call last):
  File "/Users/hoefler/sandbox/annotationframework/af/threading/importer.py", line 88, in __call__
    self.contourImage.emit(tuple(mp.iterQImages()),
  File "/Users/hoefler/sandbox/annotationframework/af/segmentation/multicolor.py", line 56, in iterQImages
    channels = range(self._reader.channels)
  File "/Users/hoefler/sandbox/annotationframework/af/imageio.py", line 110, in channels
    return self.header[self.IMAGE][0][self.CHANNEL]
KeyError: 'Sample / Pixel'
Traceback (most recent call last):
  File "/Users/hoefler/sandbox/annotationframework/af/threading/thread.py", line 34, in run
    self.worker()
  File "/Users/hoefler/sandbox/annotationframework/af/threading/importer.py", line 88, in __call__
    self.contourImage.emit(tuple(mp.iterQImages()),
  File "/Users/hoefler/sandbox/annotationframework/af/segmentation/multicolor.py", line 56, in iterQImages
    channels = range(self._reader.channels)
  File "/Users/hoefler/sandbox/annotationframework/af/imageio.py", line 110, in channels
    return self.header[self.IMAGE][0][self.CHANNEL]
KeyError: 'Sample / Pixel'
/Users/hoefler/sandbox/annotationframework/af/threading/thread.py:37: UserWarning: 'Sample / Pixel'
  warnings.warn(str(e))
```

The error message is completely unrelated. A workarround is to have a delay in the thread. (at least 50ms). 
Perhaps it helps to refactor the thread that one thread processes one image.

**Comment by rhoef** [comment]
Did not occure for quite some time....
